artifact_uri: file:///c:/Users/sahan/Desktop/MYProjects/Neonatal_incubator_displayReader/notebooks/runs/mlflow/766263836617343686/811dcfcc56e64cc69d632ab9da653530/artifacts
end_time: null
entry_point_name: ''
experiment_id: '766263836617343686'
lifecycle_stage: active
run_id: 811dcfcc56e64cc69d632ab9da653530
run_name: yolov8n-incubator-v2
source_name: ''
source_type: 4
source_version: ''
start_time: 1759817066674
status: 1
tags: []
user_id: sahan
