artifact_location: file:///c:/Users/sahan/Desktop/MYProjects/Neonatal_incubator_displayReader/notebooks/runs/mlflow/0
creation_time: 1759396634676
experiment_id: '0'
last_update_time: 1759396634676
lifecycle_stage: active
name: Default
