artifact_location: file:///c:/Users/sahan/Desktop/MYProjects/Neonatal_incubator_displayReader/notebooks/runs/mlflow/766263836617343686
creation_time: 1759396634707
experiment_id: '766263836617343686'
last_update_time: 1759396634707
lifecycle_stage: active
name: incubator
